import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header";
import Head from 'next/head';
import { UserProvider } from '@auth0/nextjs-auth0/client';
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Shopping site",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
      <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        />
      </Head>
      <UserProvider>
        <body>
          <Header></Header>
          {children}
        </body>
      </UserProvider>
    </html>
  );
}
